#!/bin/sh
if [[ $# -lt 1 ]]; then
  echo "Usage: script <folder>"
  exit 1
fi

snap_bin=/home/Zhan/repository/snap/examples/Release
folder_graphs=$1

if [ -e $folder_graphs ]; then
  if [ -d $folder_graphs ]; then
    printf "% 16s,% 9s,% 9s,% 9s,% 9s,% 9s,% 9s\n" "graphs" "V" "E" "D0" "Di0" "Do0" "Dion0"
  else
    echo "$folder_graphs is not a directory"
    exit 1
  fi
else
  echo "$folder_graphs does not exist"
  exit 1
fi

# snap netstat can only ourput to current directory
# so it'd be better to run in the same directory with dataset

(
  cd $folder_graphs;
  for graph in *.csv; do
    printf "% 16s" "$graph"
    $snap_bin/netstat -i:$graph -o:$graph 2> /dev/null |
      sed -n '20,25p' | sed -e 's/.*:\s*//g' |
      while read v; do printf ",% 9s" "$v"; done
    printf "\n"
  done
)
