#!/bin/sh
if [ $# -lt 1 ]; then
  echo "Usage: script <folder>"
  exit 1
fi

net_stat=netstat
script_home=`dirname "${BASH_SOURCE[0]}"`
snap_bin_rel0=$script_home/../snap/examples/Release
snap_bin_rel1=$script_home/../snap/examples/Debug
snap_bin_rel2=$script_home/../snap/examples/netstat
if [ -d $snap_bin_rel0 ]; then
  snap_bin=`cd $snap_bin_rel0; pwd`/
elif [ -d $snap_bin_rel1 ]; then
  snap_bin=`cd $snap_bin_rel1; pwd`/
elif [ -d $snap_bin_rel2 ]; then
  snap_bin=`cd $snap_bin_rel2; pwd`/
else # netstat is a common utility for checking network status
  echo "Please clone and compile SNAP utilities in [`cd $script_home/..; pwd`]"
  exit 1
fi

folder_graphs=$1

if [ -e $folder_graphs ]; then
  if [ -d $folder_graphs ]; then
    printf "% 16s,% 9s,% 9s,% 9s,% 9s,% 9s,% 9s\n" "graphs" "V" "E" "D0" "Di0" "Do0" "Dion0"
  else
    echo "$folder_graphs is not a directory"
    exit 1
  fi
else
  echo "$folder_graphs does not exist"
  exit 1
fi

# snap netstat can only ourput to current directory
# so it'd be better to run in the same directory with dataset

(
  cd $folder_graphs;
  for graph in *.txt; do
    printf "% 16s" "$graph"
    $snap_bin$net_stat -d:F -p:chwCv -i:$graph -o:$graph 2> /dev/null |
      sed -n '20,25p' | sed -e 's/.*:\s*//g' |
      while read v; do printf ",% 9s" "$v"; done
    printf "\n"
  done
)
